# 1. Configurações do Banco de Dados (MySQL)
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/vik_fastfood_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=vik_api_user
spring.datasource.password=virovi
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Configurações do Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 3. Configurações de JSON (Jackson)
# Isso ajuda a formatar as datas no JSON de resposta

# 4. Porta da API (Opcional)
server.port=8080